# reload conf
unbind r
bind r source-file ~/.tmux.conf

# ctrl + a as prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a last-window


# mouse on
set -g mouse on

# Using Ctrl to jump between words
set-window-option -g xterm-keys on
unbind-key -n C-Left
unbind-key -n C-Right

# set pane splitting
# set-option -g @ssh-split-keep-cwd "true"
# set-option -g @ssh-split-h-key "h"
# set-option -g @ssh-split-v-key "v"
bind-key v split-window -h  -c '#{pane_current_path}'
bind-key h split-window -c '#{pane_current_path}'

# Alt-arrow for navigation between panes
bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# set new window
bind c new-window -c "#{pane_current_path}"

# re-number windows when one is closed
set -g renumber-windows on

##############
## STATUS BAR
##############
# position
# set-option status-position top

# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, network-bandwidth, network-ping, ssh-session, attached-clients, network-vpn, weather, time, mpc, spotify-tui, playerctl, kubernetes-context, synchronize-panes
# dracula plugins 
set -g @dracula-plugins "none"

# enable powerline symbols
set -g @dracula-show-powerline true

# for left
set -g @dracula-show-left-sep ""

# for right symbol (can set any symbol you like as separator)
set -g @dracula-show-right-sep ""

# enable window flags (*)
# set -g @dracula-show-flags true

# refresh rate 
# the default is 5, it can accept any number
# set -g @dracula-refresh-rate 5

# switch the left smiley icon
# it can accept `hostname` (full hostname), `session`, `shortname` (short name), `smiley`, `window`, or any character.
set -g @dracula-show-left-icon session

# add padding to the left smiley icon
# default is 1, it can accept any number and 0 disables padding.
set -g @dracula-left-icon-padding 1

# enable high contrast pane border
# set -g @dracula-border-contrast true

# hide empty plugins
# set -g @dracula-show-empty-plugins false

## cpu-usage options
# customize label
# set -g @dracula-cpu-usage-label "CPU"

# show system load average instead of CPU usage percentage (default)
# CPU usage percentage (default) - in percentage (output: %) Load average – is the average system load calculated over a given period of time of 1, 5 and 15 minutes (output: x.x x.x x.x)
# set -g @dracula-cpu-display-load true

## weather options
# switch from default fahrenheit to celsius
set -g @dracula-show-fahrenheit false

# hide your location
set -g @dracula-show-location false

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'pschmitt/tmux-ssh-split'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
