# Use the color palette
palette = "dracula"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[directory]
truncate_to_repo = true
truncation_length = 12

[username]
show_always = true
style_user = "bold green"

[nodejs]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✖](bold red)'

[package]
disabled = true
symbol = ""